name: Copy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout other repo
      uses: actions/checkout@v4
      with:
        repository: 'NanmiCoder/MediaCrawler'
        path: 'temp-repo'
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Copy files
      run: |
        mkdir -p src
        rm -rf temp-repo/.git
        rm -f temp-repo/README.md  # 删除 README.md 文件
        rm -f temp-repo/LICENSE    # 删除 LICENSE 文件
        cp -a temp-repo/. src/
        ls -la  # 列出当前目录结构，以验证 temp-repo 的存在
        rm -rf temp-repo
        ls -la  # 再次列出，确认 temp-repo 已被删除

    - name: Commit files
      run: |
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Sync files from NanmiCoder/MediaCrawler to src directory" || echo "No changes to commit"
        git push git@github.com:JJLibra/We-mediaCrawler.git HEAD:main

    - name: Clean up temp-repo
      run: |
        ls -la
        rm -rf src
        ls -la


